- name: "config :: enable the Kubelet service"
  become: true
  ansible.builtin.service:
    name: kubelet
    enabled: yes
  
- name: "install :: prevent kubelet, kubeadm and kubectl from being upgraded"
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl