- name: "install :: updates package lists"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: upgrades package lists"
  become: true
  ansible.builtin.apt:
    upgrade: full
    force_apt_get: true

- name: "install :: adds the official Google key"
  become: true
  ansible.builtin.apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: "install :: download and add the Kubernetes GPG key"
  become: true
  ansible.builtin.shell: >
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key |
    gpg --dearmor -o /etc/apt/keyrings/k8s.gpg
  args:
    creates: /etc/apt/keyrings/k8s.gpg

- name: "install :: add the Kubernetes repository"
  become: true
  ansible.builtin.shell: >
    echo 'deb [signed-by=/etc/apt/keyrings/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' |
    tee /etc/apt/sources.list.d/k8s.list
  args:
    creates: /etc/apt/sources.list.d/k8s.list

- name: "install :: updates package lists"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: install kubelet, kubeadm and kubectl specific version"
  become: true
  ansible.builtin.apt:
    pkg:
    - kubeadm=1.30.*
    - kubelet=1.30.*
    - kubectl=1.30.*
    state: present
    force_apt_get: true